"""make patient_id nullable on diagnoses

Revision ID: 520956dc873d
Revises: 70ab5f14ed06
Create Date: 2026-03-12 17:13:48.547839

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '520956dc873d'
down_revision: Union[str, None] = '70ab5f14ed06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnoses', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('diagnoses', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
