"""add dietary plan columns to diagnoses

Revision ID: 70ab5f14ed06
Revises: 
Create Date: 2026-03-12 17:12:38.811938

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '70ab5f14ed06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('ai_dietary_plan', sa.JSON(), nullable=True))
    op.add_column('diagnoses', sa.Column('ai_routine_plan', sa.JSON(), nullable=True))
    op.add_column('diagnoses', sa.Column('ai_ayurvedic_medicines', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'ai_ayurvedic_medicines')
    op.drop_column('diagnoses', 'ai_routine_plan')
    op.drop_column('diagnoses', 'ai_dietary_plan')
    # ### end Alembic commands ###
