"""add differential_diagnoses column

Revision ID: a9a17bb661f9
Revises: 520956dc873d
Create Date: 2026-03-12 18:32:38.510281

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a9a17bb661f9'
down_revision: Union[str, None] = '520956dc873d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnoses', sa.Column('ai_differential_diagnoses', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnoses', 'ai_differential_diagnoses')
    # ### end Alembic commands ###
